name: "identity_core"
platform: "pytorch_libtorch"
max_batch_size: 16

input [
  {
    name: "INPUT__0"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]
output [
  {
    name: "OUTPUT__0"
    data_type: TYPE_UINT8
    dims: [ -1 ]
  }
]
